# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5882490268391981b98b2d094f074d447b326376953e873611210dc115428fc67164df672f494e21d621f0af7b8875bc92d55b47e571746de45556864728cc0

test:
  secret_key_base: aa28cf4ff0c4abdf6456bb045205468ef0eb42757eec6a6a151cd4b7893a71d403ee41bc2bf9a09c2d8f6ad775edded29667716bdaea1aafd251cff4a498f597

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
